title: Driven To Develop
email:
description: > # this means to ignore newlines until "baseurl:"
  The personal blog for David O'Hara, President of Improving, known speaker
  and thought leader in creating companies of culture and developing leaders.
baseurl: "" # the subpath of your site, e.g. /blog
url: http://driventodevelop.com
twitter_username: davidmohara
github_username:  davidmohara

author:
  name      : David O'Hara
  email     : david@driventodevelop.com
  url       : http://driventodevelop.com
  github    : http://github.com/davidmohara
  twitter   : http://twitter.com/davidmohara
  facebook  : http://facebook.com/davidmohara
  linkedin  : http://linkedin.com/in/davidmohara

links:
  - name:         About
    url:          /about
# highlighter:      pygments
permalink:        pretty

# Build settings
markdown: kramdown
theme: minima
gems:
  - jekyll-feed
exclude:
  - Gemfile
  - Gemfile.lock
